### PR TITLE
Remove reserved word check

### PR DESCRIPTION
**Pull request by bilalaslamseattle**

### CODE REVIEW

**Comment by ghost** [comment]
👍

**Comment by nathanboktae** [comment]
:+1:

**Comment by bilalaslamseattle** [comment]
@tmacie @nathanboktae one more proposed change (remove timestamp in future check)

**Comment by nathanboktae** [comment]
mmm that check is kinda nice. Maybe move it to an additional check like the length check?

**Comment by nathanboktae** [comment]
So why do we have the reserved work check at all?

**Comment by bilalaslamseattle** [comment]
@nathanboktae tbh we don't ... if downstream consumers like ingester and API are doing their jobs by quoting column names ... so do you recommend removing the check entirely?

**Comment by taiga418** [comment]
nit: tests for case when enid is not null but {user/account}_id is? probably not that important, so 👍

**Pull request merged**
